"""empty message

Revision ID: 02db576d7efc
Revises: 4874313c4983
Create Date: 2019-03-15 00:13:47.932727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02db576d7efc'
down_revision = '4874313c4983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('today_transaction_amount', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('team_qualified_cnt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'team_qualified_cnt')
    op.drop_column('currency', 'today_transaction_amount')
    # ### end Alembic commands ###
