"""empty message

Revision ID: 05e35cfc8aec
Revises: e26e08657715
Create Date: 2019-03-13 07:34:59.027909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e35cfc8aec'
down_revision = 'e26e08657715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_price_record',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('delta_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('transaction_cnt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('currency', sa.Column('transaction_cnt', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('current_price', sa.Numeric(precision=24, scale=8), nullable=False))
    op.add_column('order', sa.Column('payment_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'order', 'payment', ['payment_id'], ['id'])
    op.add_column('payment', sa.Column('invalid', sa.SmallInteger(), nullable=True))
    op.add_column('user', sa.Column('buy_order_cnt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'buy_order_cnt')
    op.drop_column('payment', 'invalid')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'payment_id')
    op.drop_column('order', 'current_price')
    op.drop_column('currency', 'transaction_cnt')
    op.drop_table('currency_price_record')
    # ### end Alembic commands ###
