"""empty message

Revision ID: 222412561577
Revises: b719b9877d5f
Create Date: 2019-04-14 14:22:55.259708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222412561577'
down_revision = 'b719b9877d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('order_mobile', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'order_mobile')
    # ### end Alembic commands ###
