"""empty message

Revision ID: 3e6777f15e93
Revises: 222412561577
Create Date: 2019-04-14 16:16:38.304943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6777f15e93'
down_revision = '222412561577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_order_task', sa.Column('order_cnt', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_order_task', 'order_cnt')
    # ### end Alembic commands ###
