"""empty message

Revision ID: 4874313c4983
Revises: 05e35cfc8aec
Create Date: 2019-03-14 07:38:21.309269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4874313c4983'
down_revision = '05e35cfc8aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('grand_total_balance', sa.Numeric(precision=24, scale=8), nullable=False))
    op.add_column('user', sa.Column('continuous_buy_cnt', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_community_node', sa.SmallInteger(), nullable=True))
    op.add_column('user', sa.Column('today_have_transaction', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'today_have_transaction')
    op.drop_column('user', 'is_community_node')
    op.drop_column('user', 'continuous_buy_cnt')
    op.drop_column('assets', 'grand_total_balance')
    # ### end Alembic commands ###
