"""empty message

Revision ID: 5caf53f195fa
Revises: 3e6777f15e93
Create Date: 2019-04-14 22:47:26.350128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5caf53f195fa'
down_revision = '3e6777f15e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_old',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('match_user_id', sa.String(length=36), nullable=True),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('hold_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('match_at', sa.DateTime(), nullable=True),
    sa.Column('proof_img', sa.Text(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['match_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_old')
    # ### end Alembic commands ###
