"""empty message

Revision ID: 629f56ca60ea
Revises: e1e52aa39ffd
Create Date: 2019-03-11 06:59:46.065897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629f56ca60ea'
down_revision = 'e1e52aa39ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('transaction_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'transaction_level')
    # ### end Alembic commands ###
