"""empty message

Revision ID: 6d35caa63912
Revises: 
Create Date: 2019-03-08 23:52:46.390055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d35caa63912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.Column('locked', sa.SmallInteger(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('permission', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('captcha_pin_code',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pin_code_signature', sa.String(length=256), nullable=False),
    sa.Column('try_times', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usd_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_schedule_task',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp')
    )
    op.create_table('email_pin_code',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pin_code_signature', sa.String(length=256), nullable=False),
    sa.Column('try_times', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('sms_pin_code',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pin_code_signature', sa.String(length=256), nullable=False),
    sa.Column('try_times', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=True),
    sa.Column('country_code', sa.String(length=16), nullable=True),
    sa.Column('mobile', sa.String(length=16), nullable=True),
    sa.Column('login_email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('security_password', sa.String(length=256), nullable=True),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('locked', sa.SmallInteger(), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('sponsor_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.SmallInteger(), nullable=True),
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('assets',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_balance', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('community_balance', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('transaction_balance', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets_balance_record',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('delta_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('assets_type', sa.SmallInteger(), nullable=False),
    sa.Column('record_type', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_info',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('client_ip', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_holder', sa.String(length=64), nullable=True),
    sa.Column('bank', sa.String(length=128), nullable=True),
    sa.Column('branch', sa.String(length=256), nullable=True),
    sa.Column('card_number', sa.String(length=64), nullable=True),
    sa.Column('wechat', sa.String(length=64), nullable=True),
    sa.Column('alipay', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register_schedule_task',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register_schedule_task')
    op.drop_table('payment')
    op.drop_table('login_info')
    op.drop_table('assets_balance_record')
    op.drop_table('assets')
    op.drop_table('user')
    op.drop_table('sms_pin_code')
    op.drop_table('setting')
    op.drop_table('email_pin_code')
    op.drop_table('daily_schedule_task')
    op.drop_table('currency')
    op.drop_table('captcha_pin_code')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
