"""empty message

Revision ID: 817cc8bae493
Revises: 7d67ad515967
Create Date: 2019-03-09 23:36:25.051338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '817cc8bae493'
down_revision = '7d67ad515967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('address', sa.String(length=64), nullable=True))
    op.add_column('payment', sa.Column('alipay_image', sa.String(length=512), nullable=True))
    op.add_column('payment', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('payment', sa.Column('remark', sa.String(length=64), nullable=True))
    op.add_column('payment', sa.Column('type', sa.SmallInteger(), nullable=False))
    op.add_column('payment', sa.Column('wechat_image', sa.String(length=512), nullable=True))
    op.drop_column('payment', 'branch')
    op.drop_column('payment', 'card_holder')
    op.add_column('user', sa.Column('allow_transaction', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('wechat', sa.String(length=64), nullable=True))
    op.drop_column('user', 'received_reward')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('received_reward', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'wechat')
    op.drop_column('user', 'allow_transaction')
    op.add_column('payment', sa.Column('card_holder', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('payment', sa.Column('branch', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('payment', 'wechat_image')
    op.drop_column('payment', 'type')
    op.drop_column('payment', 'remark')
    op.drop_column('payment', 'name')
    op.drop_column('payment', 'alipay_image')
    op.drop_column('payment', 'address')
    # ### end Alembic commands ###
