"""empty message

Revision ID: e26e08657715
Revises: 629f56ca60ea
Create Date: 2019-03-11 23:22:50.888416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26e08657715'
down_revision = '629f56ca60ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('match_user_id', sa.String(length=36), nullable=True),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('hold_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('match_at', sa.DateTime(), nullable=True),
    sa.Column('proof_img', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
